# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tyler Simko
tagline:             'A new adventure.'
description:         'You found the hidden drawer. Explore a bit. Made by <a href="https://twitter.com/tylersimko" target="_blank">@tylersimko</a>.'
url:                 http://tylersimko.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Tyler Simko
  url:               https://twitter.com/tylersimko
  email:             tyler@o8labs.com

# Custom vars
version:             1.0.0
