# Site Settings
baseurl: 		""
title: 			Tyler Simko's Blog

name: 			Hashtag <i>for</i> Jekyll
description: 	A beautifully contemporary and elegant Jekyll theme
url: 			"http://tylersimko.github.io"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		tylersimko
email: 			tyler@o8labs.com

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2014 Indiqo.	

# Build Settings
permalinks: 	pretty